services:
  server:
    environment:
      ENV: local
      RUN_MIGRATIONS: 1
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: cdb
    image: cdb:latest
    entrypoint: /app/docker/compose-entrypoint.sh
    volumes:
      - ./.air.toml:/app/.air.toml
    build: 
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname cdb --username postgres --timeout 1"]
      interval: 0s
      timeout: 5s
      retries: 5
