services:
  server:
    environment:
      ENV: local
      RUN_MIGRATIONS: 1
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: cdb
      FRONTEND_LOCATION: http://frontend:5173
      JWT_SIGNING_KEY: insecure
    image: golang:1.22
    entrypoint: /app/docker/compose-entrypoint.sh
    working_dir: /app
    volumes:
      - .:/app
      - cdb-go-path:/go
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    image: node:lts
    entrypoint: /app/docker/compose-entrypoint.sh
    command: [frontend]
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./docker:/app/docker
      - cdb-node-modules:/app/node_modules
    ports:
      - "5173:5173"

  documentation:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - "9000:8000"

  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname cdb --username postgres --timeout 1"]
      interval: 0s
      timeout: 5s
      retries: 5

volumes:
  cdb-node-modules:
  cdb-go-path:
