#!/usr/bin/env bash

if [[ ! -x $(which migrate) ]]; then
    echo "Install the golang-migrate CLI."
    printf "\tInstructions available here: https://github.com/golang-migrate/migrate/tree/master/cmd/migrate\n"
    exit 1
fi

function print_usage() {
    echo "Usage: ./scripts/create-migration <NAME>

This will create an up and down migration files in the migrations directory at
the root of the repository with the given name. You must then populate those SQL
files accordingly.

Example:

    ./scripts/create-migration create_environments_table"
}

if [[ $# == 0 || "$1" == "help" ]]; then
    print_usage
    exit 0
fi

cd "$(git rev-parse --show-toplevel)" || exit 10
migrate create -ext sql -dir migrations -seq "$@"
