#!/usr/bin/env bash

if [[ ! -x $(which air) ]]; then
    echo "Install air to run the server with live reload:"
    echo "https://github.com/cosmtrek/air"
    air
else
    go run ./cmd/cdbd server
fi
