#!/usr/bin/env bash

set -o errexit

# Check if running inside docker:
# https://stackoverflow.com/a/20012536
if [[ $(cat /proc/1/cgroup 2>/dev/null) != '/' ]]; then
    if [[ ! -x $(which golangci-lint 2>/dev/null) ]]; then
        echo "Linter not installed, installing..."
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" v1.57.2
    fi

    echo "Linting.."
    golangci-lint run --fix
else
    docker compose exec -it server /app/scripts/lint
fi

