apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdb.fullname" . }}
  labels:
    {{- include "cdb.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- if .Values.postgresql.enabled }}
  PGHOST: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
