apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdb.fullname" . }}
  labels:
    {{- include "cdb.labels" . | nindent 4 }}
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
